export const rawMessageList = {
    "00": ["Bonjour, nous sommes des journalistes faisant un reportage sur l\u2019exp\u00e9rience du Professeur Tournesol.\nSeriez-vous disponible pour r\u00e9pondre \u00e0 quelques questions ?"],
    "10": ["Qui travaille dans votre laboratoire ?"],
    "11": ["Au fait, c'est où la Sildavie ?"],
    "20": ["Connaissiez-vous le professeur Tournesol avant de travailler sur la gaz vert ?"],
    "21": ["Tout va bien dans votre labo ? Pas trop d\u2019exposition m\u00e9diatique ?"],
    "30": ["Comment avez-vous entendu parler de l\u2019exp\u00e9rience de Tournesol ?"],
    "40": ["Je vous remercie ! Maintenant si vous \u00eates d\u2019accord, on aimerait aborder votre exp\u00e9rience plus en d\u00e9tail."],
    "50": ["Tout d'abord, avez-vous r\u00e9ussi \u00e0 reproduire l\u2019exp\u00e9rience ? Avez-vous rencontr\u00e9 des impr\u00e9vus?"],
    "51": ["Est-ce que vous avez valid\u00e9 l\u2019exp\u00e9rience du professeur Tournesol parce que vous \u00eates amis ?"],
    "52": ["Il y a plus important que l’expérience… saviez-vous que quelqu’un du labo a flashé sur vous et aimerait venir visiter la Sildavie ?"],
    "60": ["Et alors vous avez v\u00e9rifi\u00e9 ses r\u00e9sultats ?"],
    "61": ["Est-ce que vous avez v\u00e9rifi\u00e9 qu\u2019elle suivait bien le m\u00eame protocole ?"],
    "62": ["Peut-\u00eatre que vous n\u2019aviez pas utilis\u00e9 la m\u00eame lumi\u00e8re qu\u2019elle ?"],
    "70": ["Et malgr\u00e9 \u00e7a, vous avez quand m\u00eame valid\u00e9 l\u2019exp\u00e9rience ?"],
    "71": ["Vous n\u2019avez pas retent\u00e9 l\u2019exp\u00e9rience apr\u00e8s son d\u00e9part ?"],
    "72": ["Comment s\u2019appelait cette technicienne ?"],
    "73": ["Vous n\u2019avez pas beaucoup de charisme si vous n\u2019arrivez m\u00eame pas \u00e0 retenir une coll\u00e8gue le temps de v\u00e9rifier son travail..."],
    "80": ["Et vous savez pourquoi vos deux coll\u00e8gues \u00e9taient tr\u00e8s motiv\u00e9s pour soutenir Tournesol ?"],
    "81": ["Finalement, vous pensez que le gaz vert détruit beaucoup de CO2 ou pas ?"],
    "82": ["Avez vous entendu parler d’un autre laboratoire qui aurait reproduit l’expérience ?"],
    "90": ["Merci beaucoup pour vos r\u00e9ponses !\nAu revoir !"],
    "91": ["Qu'est-ce que la g\u00e9oing\u00e9nierie ?"],
    "92": ["Est-ce qu\u2019on pourrait revenir sur certaines questions ?"],
    "93": ["Vous savez qu’on a vu vos collègues sur une île, à un colloque luxueux donnée par une entreprise de géoingénierie il y a 6 mois ?"],
    "94": ["Connaissez-vous d'autres gens qui ont voulu reproduire l'expérience de Tournesol?"],
    "100":["Recentrons un peu la conversation."],
    "110":["ELISABETH"],
    "120":["VAADHOO"],
    "130":[""],
    "140":["Vous voulez dire qu’ils cachent intentionnellement les expériences qui n’ont pas marché ? C’est une accusation grave !"]
}

export const rawResponseList = {
    "00": ["Bonjour !\nEn ce moment c\u2019est un peu le rush, mais j\u2019ai un peu de temps oui !"],
    "10": [" Le laboratoire Da Silva est constitué de 4 personnes : Déborah et Joshua, qui sont chercheurs à temps partiel, Valentina, chercheuse à temps plein, et moi, directeur du laboratoire. On étudie la santé des animaux."],
    "11": ["Je parle \u00e0 des journalistes ou \u00e0 des \u00e9l\u00e8ves de primaire ? La g\u00e9o \u00e7a s\u2019apprend dans les manuels scolaires, pas les bandes dessin\u00e9es!"],
    "20": ["Non on ne se connaissait pas, en effet dans mon labo Sildave on ne travaille pas avec des plantes d’habitude."],
    "21": ["Pour être honnête ça ne va pas fort, l'ambiance est un peu tendue entre nous... Depuis cette histoire d'expérience sur le gaz vert justement :/"],
    "30": ["C’est mon collègue, Joshua, qui a proposé qu’on reproduise leur expérience. J’ai refusé au début car on étudie surtout les animaux chez nous, mais il a insisté en disant que c’était peut-être une découverte majeure, ça m’a intéressé."],
    "40": ["Avec plaisir je vous \u00e9coute"],
    "50": ["Au début, tout s'est très bien passé, nous avons respecté leur protocole à la lettre et les mesures de cellules noires se sont bien déroulées. Mais au moment d'étudier les résultats, nous nous sommes retrouvés avec une courbe complètement aléatoire, comme si le gaz vert ne faisait rien de particulier! J'ai trouvé ça étrange et j'ai mis le professeur Tournesol au courant. Très serviable, il nous a envoyé sa meilleure technicienne pour nous aider à refaire l'expérience. Seulement voilà, quand elle est arrivée, elle a dit qu'on la gênait et elle a exigé qu'on la laisse faire l'expérience seule! La courbe qu'elle a trouvé lors de cette deuxième expérience était très similaire à la courbe du labo Tournesol. Je vous envoie ces deux courbes","$stat"],
    "51": ["Vous êtes sûrs que vous avez lu mes messages? Je ne connaissais pas ce professeur Tournesol avant cette expérience, je suis un chercheur sérieux qui fait bien son travail! Et contrairement à ce que vous pouvez penser, je ne \"valide\" pas son expérience! C'est plus compliqué que ça..."],
    "52": ["AH BON ? Qu’est ce que vous me racontez là. Vous ne vous moquez pas de moi j’espère ! Et comment s'appellerait cette personne?"],
    "60": ["Oui, et les quantit\u00e9s de gaz vert dans les bocaux ne correspondaient pas aux \u00e9tiquettes ! Il y avait eu de grosses erreurs de manipulation, et cela rendait l\u2019exp\u00e9rience invalide.\nMais la technicienne \u00e9tait hyper press\u00e9e et \u00e9tait d\u00e9j\u00e0 repartie avec les mesures qu\u2019elle avait obtenue !"],
    "61": ["Au début on est restés avec elle, mais elle a fini par nous mettre dehors car \" on brisait sa concentration \". Ca fait bizarre de se faire virer de son propre lieu de travail, mais après tout, c'était elle l'experte en cellules noires, comme je vous l'ai dit ce n'est pas la spécialité de notre labo Sildave."],
    "62": ["Tu veux faire mon boulot à ma place toi :p Plus sérieusement, nous avons acheté les mêmes lampes de culture que le labo Tournesol donc le problème n'é'tait pas là."],
    "70": ["Bonne question !  On s\'est un peu disputés entre nous. En principe, pour qu’une expérience soit considérée comme fiable, elle doit être reproduite par des labos indépendants, hors là c’est Elisabeth qui a reproduit l’expérience chez nous, ce n’est pas du tout une reproduction indépendante ! Valentina et moi voulions retirer notre soutien au labo Tournesol, mais Joshua et Déborah n'avaient aucun problème avec ces embrouilles et ont voulu soutenir tout de même le Prof Tournesol. Le temps qu\'on règle nos comptes, Tournesol avait déjà crié sous tous les toits qu'il avait notre soutien, et ce qu'on avait à dire n'intéressait plus personne :("],
    "71": ["J'aurais aimé reproduire leur expérience à l'aveugle, pour éliminer le biais de l'observateur, mais cela aurait coûté du temps et de l'argent, et nous avons d'autres priorités. Même si je vous avoue que Joshua me relance régulièrement sur ce sujet."],
    "72": ["Elle s\u2019appelait Elisabeth si je me souviens bien\u2026 Gentille comme tout, bien qu\u2019un peu stress\u00e9e sur les bords."],
    "73": ["Toi tu veux go\u00fbter \u00e0 des patates sildaves non ? Quand je sors du labo je vais dans l\u2019octogone alors attention à toi..."],
    "80": ["Eh bien je ne sais pas trop, mais ils avaient l\u2019air int\u00e9ress\u00e9s pour du travail qu\u2019ils font en freelance \u00e0 c\u00f4t\u00e9 de leur boulot dans notre labo sildavien.","Je vous envoie une capture d'écran de notre conversation si \u00e7a vous int\u00e9resse !","$chat"],
    "81": ["Je n’en sais rien, en tout cas l’expérience de Tournesol ne prouve rien d’un point de vue scientifique. Je pense cependant que le labo Tournesol est convaincu du phénomène. Ça fait 2 ans qu’ils bossent sur le sujet, il sont très motivés… Dans ces conditions, on peut facilement « oublier » les expériences qui ne fonctionnement pas et se rappeler seulement de celles qui fonctionnent."],
    "82": ["Pas exactement, mais un labo parisien a voulu tester l’expérience à l’aveugle. C’est intéressant parce qu’on peut savoir si la méthode de mesure est fiable en faisant à l’aveugle. Une certaine Fatima quelque chose… Le prof Tournesol ou Elisabeth seront sûrement plus renseignés !"],
    "90": ["Avec plaisir! Je vous encourage fortement à aller voir les autres labos qui ont travaillé sur le sujet !"],
    "91": ["Il me semble que c\u2019est des gens qui veulent modifier le climat \u00e0 grande \u00e9chelle en utilisant la technologie. Du peu que j\u2019en ai lu, pour l\u2019instant c\u2019est plus dangereux que b\u00e9n\u00e9fique."],
    "92": ["Contrairement \u00e0 ce que vous pourriez imaginer j\u2019ai du travail, mais je peux vous accorder encore 2 min :p"],
    "93": ["Ah bon ? Pourriez-vous me dire le nom de l'île en question ? J’aimerais vérifier, ils ne veulent pas me parler de leur boulot à côté du labo."],
    "100":["Oui si tu as des questions plus s\u00e9rieuses..."],
    "110":["Eh ben le journalisme ce n’est plus ce que c’était de nos jours… Si vous comptez raconter n’importe quoi je vous préviens je me déconnecte !"],
    "111":["Je ne sais pas quoi répondre! Sans fausse modestie, je sais que j'ai du charme et un très bon caractère mais quand même... En même temps la pauvre, des vacances lui feraient du bien… \n J’ai l’impression qu’elle est sous l’eau depuis qu’ils travaillent sur le gaz vert, elle m'a dit que c’est elle qui fait presque toutes les mesures à l’oeil nu, elle enchaîne les semaines de 50h… Je crois que prof Tournesol lui met un trop la pression, et c'est jamais bon de travailler en étant fatigué ou stressé, on fait plus d'erreurs."],
    "120":["Mmmmh je ne trouve rien sur un colloque qui s’est déroulé là-bas… Il faudrait vérifier vos sources !"],
    "121":["En effet, ils étaient tous les deux en voyage d’affaire il y a 6 mois ! Alors il travaillent aussi pour Totalternative? Pas étonnant qu’ils veuillent valider l’expérience, Totalternative vend du gaz vert, imaginez comment leurs ventes vont exploser si le labo Tournesol prouve sa théorie! Je comprends mieux pourquoi ils voulaient à tout prix soutenir le prof Tournesol, ils ne sont pas du tout indépendants dans cette affaire! Merci de m'avoir révélé ça, ils vont passer un sale quart d'heure demain en réunion!!"],
    "130":["EXIT"],
    "140":["Je n’irais pas aussi loin! Ils m’ont l’air de bonne foi. Mais c’est bien connu, et c’est pareil pour tout le monde, quand on veut prouver quelque chose, on a tendance à retenir seulement les exemples qui vont dans notre sens! Ce n’est pas forcément de la mauvaise foi car ça peut être inconscient. C’est pour ça que dans la recherche scientifique, il faut prendre en compte TOUS les résultats pour être sûr de ne pas s’égarer en chemin."]
}

export const rawSectionList = [
    [{ sectionId: 0, choiceId: 0, goTo: 1 }],   
    [{ sectionId: 1, choiceId: 0,goTo: 2 }, { sectionId: 1, choiceId: 1,goTo: 2 }],
    [{ sectionId: 2, choiceId: 0,goTo: 3 }, { sectionId: 2, choiceId: 1, goTo: 3 }],
    [{ sectionId: 3, choiceId: 0, goTo: 4 }],
    [{ sectionId: 4, choiceId: 0, goTo: 5 }],
    [{ sectionId: 5, choiceId: 0, goTo: 6 }, { sectionId: 5, choiceId: 1, goTo: 10 }, { sectionId: 5, choiceId: 2, goTo: 11 }],
    [{ sectionId: 6, choiceId: 0, goTo: 7 }, { sectionId: 6, choiceId: 1, goTo: 6 }, { sectionId: 6, choiceId: 2, goTo: 6 }],
    [{ sectionId: 7, choiceId: 0, goTo: 8 }, { sectionId: 7, choiceId: 1, goTo: 7 }, { sectionId: 7, choiceId: 2, goTo: 7 }, { sectionId: 7, choiceId: 3, goTo: 10 }],
    [{ sectionId: 8, choiceId: 0, goTo: 9 }, { sectionId: 8, choiceId: 1, goTo: 14 }, { sectionId: 8, choiceId: 2, goTo: 8 }],
    [{ sectionId: 9, choiceId: 0, goTo: 13 }, { sectionId: 9, choiceId: 1, goTo: 9 }, { sectionId: 9, choiceId: 2 , goTo: 5}, { sectionId: 9, choiceId: 3, goTo: 12}],
    [{ sectionId: 10, choiceId: 0, goTo: 5 }],
    [{ sectionId: 11, choiceId: 0, goTo: 5, isInput : true },{ sectionId: 11, choiceId: 1, goTo: 5, isInput : true }],
    [{ sectionId: 12, choiceId: 0, goTo: 9, isInput : true },{ sectionId: 12, choiceId: 1, goTo: 9, isInput : true }],
    [{ sectionId: 13, choiceId: 0, goTo: 13 }],
    [{ sectionId: 14, choiceId: 0, goTo: 8 }],
]