export const rawMessageList = {
    "00": ["Bonjour, nous sommes des journalistes faisant un reportage sur l\u2019exp\u00e9rience du Professeur Tournesol.\nSeriez-vous disponible pour r\u00e9pondre \u00e0 quelques questions ?"],
    "10": ["Depuis combien de temps travaillez-vous dans votre laboratoire ?"],
    "11": ["C\u2019est o\u00f9 la Sildavie ?"],
    "20": ["Connaissiez-vous le professeur Tournesol avant qu\u2019il vous contacte ?"],
    "21": ["Tout va bien dans votre labo ? Pas trop d\u2019exposition m\u00e9diatique ?"],
    "30": ["Comment avez-vous entendu parler de l\u2019exp\u00e9rience de Tournesol ?"],
    "40": ["Je vous remercie ! Maintenant si vous \u00eates d\u2019accord on aimerait aborder votre exp\u00e9rience plus en d\u00e9tail."],
    "50": ["Tout d'abord, avez-vous r\u00e9ussi \u00e0 reproduire l\u2019exp\u00e9rience ? Avez-vous rencontr\u00e9 des impr\u00e9vus?"],
    "51": ["Est-ce que vous avez valid\u00e9 l\u2019exp\u00e9rience du professeur Tournesol parce que vous \u00eates amis ?"],
    "52": ["Il y a plus important que l’expérience… saviez-vous que quelqu’un du labo a flashé sur vous et aimerait venir visiter la Sildavie ?"],
    "60": ["Et alors vous avez v\u00e9rifi\u00e9 ses r\u00e9sultats ?"],
    "61": ["Est-ce que vous avez v\u00e9rifi\u00e9 qu\u2019elle suivait bien le m\u00eame protocole ?"],
    "62": ["Peut-\u00eatre que vous n\u2019aviez pas utilis\u00e9 la m\u00eame lumi\u00e8re qu\u2019elle ?"],
    "70": ["Et malgr\u00e9 \u00e7a, vous avez quand m\u00eame valid\u00e9 l\u2019exp\u00e9rience ?"],
    "71": ["Vous n\u2019avez pas retent\u00e9 l\u2019exp\u00e9rience apr\u00e8s son d\u00e9part ?"],
    "72": ["Comment s\u2019appelait cette technicienne ?"],
    "73": ["Vous n\u2019avez pas beaucoup de charisme si vous n\u2019arrivez m\u00eame pas \u00e0 retenir une coll\u00e8gue le temps de v\u00e9rifier son travail..."],
    "80": ["Et vous savez pourquoi vos deux coll\u00e8gues \u00e9taient tr\u00e8s motiv\u00e9s pour soutenir Tournesol ?"],
    "81": ["Mais nous ne comprenons pas, vous avez valid\u00e9 l\u2019exp\u00e9rience ou non?"],
    "90": ["Merci beaucoup pour vos r\u00e9ponses !\nAu revoir !"],
    "91": ["C\u2019est quoi la g\u00e9oing\u00e9nierie ?"],
    "92": ["Est-ce qu\u2019on pourrait revenir sur certaines questions ?"],
    "93": ["Vous savez qu\u2019on a vu vos coll\u00e8gues sur une \u00eele, \u00e0 un gala luxueux donn\u00e9e par une entreprise de g\u00e9oing\u00e9nierie ?"],
    "100": ["Recentrons un peu la conversation."],
    "110": ["ELISABETH"],
    "120": ["MALDIVES"],
    "130": ["*se d\u00e9connecter*"]
}

export const rawResponseList = {
    "00": ["Bonjour !\nEn ce moment c\u2019est un peu le rush mais j\u2019ai un peu de temps oui !", "$stat"],
    "10": ["\u00c7a va faire 10 ans, bient\u00f4t.\nOhlala le coup de vieux\u2026\nJ\u2019ai beaucoup de coll\u00e8gues qui ont quitt\u00e9 la recherche depuis."],
    "11": ["Je parle \u00e0 des journalistes ou \u00e0 des \u00e9l\u00e8ves de primaire ? La g\u00e9o \u00e7a s\u2019apprend dans les manuels scolaires, pas les bandes dessin\u00e9es ?"],
    "20": ["Oui, je l\u2019avais crois\u00e9 dans des conf\u00e9rences il y a quelques ann\u00e9es et on avait un peu parl\u00e9, nous sommes tous les deux biologistes apr\u00e8s tout."],
    "21": ["Pour \u00eatre honn\u00eate \u00e7a ne va pas fort, vos coll\u00e8gues ne viennent pas trop vous voir, par contre l\u2019ambiance est un peu tendu entre nous..."],
    "30": ["C\u2019est lui-m\u00eame qui m\u2019a contact\u00e9, il m\u2019a demand\u00e9 si je pouvais lui rendre un service en reproduisant son exp\u00e9rience, et mon \u00e9quipe \u00e9tait ok !", "\nOn a reproduit leur protocole \u00e0 la lettre et on a regard\u00e9 ce qu\u2019il se passait"],
    "40": ["Avec plaisir je vous \u00e9coute"],
    "50": ["A la base on avait fait tout bien, respect\u00e9 leur protocole et tout. Seulement au moment de regarder les r\u00e9sultats on a obtenu des mesures qui semblaient al\u00e9atoires ! Je vous envoie notre courbe !", "$stat", "Alors j\u2019ai rappel\u00e9 le prof Tournesol en lui disant qu\u2019on  ne trouvait pas du tout pareil. Il m\u2019a r\u00e9pondu \u00ab pas de soucis, je vous envoie ma meilleure technicienne elle va vous aider !\n\nAlors elle arrive, tr\u00e8s gentille et tout mais elle nous dit qu\u2019on s\u2019y est pris n\u2019importe comment et elle insiste pour s\u2019occuper elle-m\u00eame de l\u2019exp\u00e9rience. Et l\u00e0 elle a trouv\u00e9 des r\u00e9sultats qui semblaient similaires \u00e0 ceux que son labo a trouv\u00e9.", "$chat"],
    "51": ["Fr\u00e9rot tu crois que je suis un scientifique ou un mafieux ? Dans mon boulot on trouve pas quelque chose parce qu'on veut le trouver, \u00e7a c'est de l'amateurisme!"],
    "52": ["AH BON ? Qu’est ce que vous me racontez là. Vous ne vous moquez pas de moi j’espère ! donnez moi son nom !!"],
    "60": ["Oui, et les quantit\u00e9s de gaz vert dans les bocaux ne correspondaient pas aux \u00e9tiquettes ! Il y avait eu de grosses erreurs de manipulation, et cela rendait l\u2019exp\u00e9rience invalide.\nMais la technicienne \u00e9tait hyper press\u00e9e et \u00e9tait d\u00e9j\u00e0 repartie avec les mesures qu\u2019elle avait obtenue !"],
    "61": ["Au d\u00e9but on est rest\u00e9s avec elle, mais elle a fini par nous mettre dehors car \u00ab on brisait sa concentration \u00bb.\nCa fait bizarre de se faire virer de son propre lieu de travail, mais elle est pas m\u00e9chate alors on a du la laisser tranquille !"],
    "62": ["Tu veux faire mon boulot \u00e0 ma place toi ?\nPlus s\u00e9rieusement, nous avons achet\u00e9 les m\u00eames lampes de culture que le labo Tournesol donc le probl\u00e8me n\u2019\u00e9tait pas l\u00e0."],
    "70": ["Bonne question !\nOn s\u2019est un peu disput\u00e9s entre nous. Une coll\u00e8gue et moi trouvions l\u2019affaire trop fumeuse et voulions laisser tomber.\nNos deux autres coll\u00e8gues, Joshua et *** , n\u2019avaient aucun probl\u00e8me avec ces embrouilles et ont voulu soutenir tout de m\u00eame le Prof Tournesol. Le temps qu\u2019on r\u00e8gle nos comptes, Tournesol avait d\u00e9j\u00e0 cri\u00e9 sous tous les toits qu\u2019il avait notre soutien, et ce qu\u2019on avait \u00e0 dire n\u2019int\u00e9ressait plus personne :("],
    "71": ["Non, j\u2019avoue que l\u2019on avait d\u2019autres dossiers plus importants en cours, et on a pas de temps et d\u2019argent \u00e0 volont\u00e9 malheureusement."],
    "72": ["Elle s\u2019appelait Elisabeth si je me souviens bien\u2026 Gentille comme tout, bien qu\u2019un peu stress\u00e9e sur les bords."],
    "73": ["Toi tu veux go\u00fbter \u00e0 des patates sildaves non ? Quand je sors du labo je vais dans l\u2019octogone attention hein..."],
    "80": ["Eh bien je ne sais pas trop, mais ils avaient l\u2019air int\u00e9ress\u00e9s pour du taf qu\u2019ils font en freelance \u00e0 c\u00f4t\u00e9 de leur boulot dans notre labo sildavien.\n\nJe vous envoie un screen de notre conversation si \u00e7a vous int\u00e9resse !", "$stat"],
    "81": ["oUi oN a VaLiDE l\u2019eXPeRiEncE\u2026 vous lisez mes messages ou pas ? C\u2019est un peu plus compliqu\u00e9 que \u00e7a ! En tout cas l\u2019exp\u00e9rience r\u00e9alis\u00e9e par Elisabeth chez nous n\u2019\u00e9tait pas ok !"],
    "90": ["EXIT"],
    "91": ["Il me semble que c\u2019est des gens qui veulent modifier le climat \u00e0 grande \u00e9chelle en utilisant la technologie. Du peu que j\u2019en ai lu, pour l\u2019instant c\u2019est plus dangereux que b\u00e9n\u00e9fique."],
    "92": ["Contrairement \u00e0 ce que vous pourriez imaginer j\u2019ai du travail, mais je peux vous accorder encore 2 min :p"],
    "93": ["Ah bon ? Quelle île ? J’aimerais vérifier, ils ne veulent pas me parler de leur boulot à côté du labo."],
    "100": ["Oui si tu as des questions plus s\u00e9rieuses..."],
    "110": ["Eh ben le journalisme ce n’est plus ce que c’était de nos jours… Si vous comptez raconter n’importe quoi je vous préviens je me déconnecte !"],
    "111": ["Je sais pas quoi répondre moi ! On ne s’est vus qu’une fois ! En même temps la pauvre, des vacances lui feraient du bien… J’ai l’impression qu’elle est sous l’eau depuis qu’ils ont commencé cette expérience, elle me disait que c’est elle qui faisait presque toutes les mesures à l’oeil nu, elle enchaîne les journées de 50h… Le prof Tournesol lui met un peu trop la pression je trouve."],
    "120": ["Mmmmh j’ai bien regardé et ils n’apparaissent nulle part, il faudrait vérifier vos sources je pense..."],
    "121": ["En effet, je suis allé voir des photos sur internet et j’ai vu leurs deux têtes ! Et vous dites que votre comptable les a croisés là-bas ? Pas étonnant qu’ils soient intéressés par l’expérience alors, Totalternative vend du gaz vert, imaginez comment leurs ventes vont exploser maintenant que l’expérience du prof Tournesol est publique !"],
    "130": ["EXIT"]
}

export const rawSectionList = [
    [{ sectionId: 0, choiceId: 0, goTo: 1 }],
    [{ sectionId: 1, choiceId: 0, goTo: 2 }, { sectionId: 1, choiceId: 1, goTo: 2 }],
    [{ sectionId: 2, choiceId: 0, goTo: 3 }, { sectionId: 2, choiceId: 1, goTo: 3 }],
    [{ sectionId: 3, choiceId: 0, goTo: 4 }],
    [{ sectionId: 4, choiceId: 0, goTo: 5 }],
    [{ sectionId: 5, choiceId: 0, goTo: 6 }, { sectionId: 5, choiceId: 1, goTo: 10 }, { sectionId: 5, choiceId: 2, goTo: 11 }],
    [{ sectionId: 6, choiceId: 0, goTo: 7 }, { sectionId: 6, choiceId: 1, goTo: 6 }, { sectionId: 6, choiceId: 2, goTo: 6 }],
    [{ sectionId: 7, choiceId: 0, goTo: 8 }, { sectionId: 7, choiceId: 1, goTo: 7 }, { sectionId: 7, choiceId: 2, goTo: 7 }, { sectionId: 7, choiceId: 3, goTo: 10 }],
    [{ sectionId: 8, choiceId: 0, goTo: 9 }, { sectionId: 8, choiceId: 1, goTo: 10 }],
    [{ sectionId: 9, choiceId: 0, goTo: 13 }, { sectionId: 9, choiceId: 1, goTo: 9 }, { sectionId: 9, choiceId: 2, goTo: 10 }, { sectionId: 9, choiceId: 3, goTo: 12 }],
    [{ sectionId: 10, choiceId: 0, goTo: 5 }],
    [{ sectionId: 11, choiceId: 0, goTo: 5, isInput: true }, { sectionId: 11, choiceId: 1, goTo: 5, isInput: true }],
    [{ sectionId: 12, choiceId: 0, goTo: 9, isInput: true }, { sectionId: 12, choiceId: 1, goTo: 9, isInput: true }],
    [{ sectionId: 13, choiceId: 0, goTo: 13 }],
]